CREATE TABLE t_mock_project_user
(
    id           int GENERATED BY DEFAULT AS IDENTITY,
    user_name    varchar(255) NOT NULL,
    project_code varchar(255) NOT NULL,
    authorities  varchar(255),
    creator      varchar(255),
    create_date  timestamp,
    PRIMARY KEY (id)
);

CREATE INDEX idx_mock_project_user_code ON t_mock_project_user (project_code);
CREATE INDEX idx_mock_project_user_name ON t_mock_project_user (user_name);
