CREATE TABLE t_mock_log
(
    id          int GENERATED BY DEFAULT AS IDENTITY,
    user_name   varchar(255),
    log_name    varchar(8192),
    data_id     int,
    log_message text,
    log_type    varchar(255),
    log_result  varchar(255),
    log_data    text,
    log_time    bigint,
    ip_address  varchar(1024),
    headers     text,
    exceptions  text,
    extend1     longtext,
    extend2     longtext,
    creator     varchar(255),
    create_date datetime,
    PRIMARY KEY (id)
);
