CREATE TABLE t_mock_scenario
(
    id            int GENERATED BY DEFAULT AS IDENTITY,
    group_id      int,
    scenario_name varchar(255),
    scenario_code varchar(64),
    description   text,
    status        int,
    creator       varchar(255),
    create_date   timestamp,
    modifier      varchar(255),
    modify_date   timestamp,
    PRIMARY KEY (id)
);

ALTER TABLE t_mock_group ADD COLUMN active_scenario_code varchar(64);

ALTER TABLE t_mock_request ADD COLUMN scenario_code varchar(64);
