ALTER TABLE
    t_mock_group
    ADD
        COLUMN project_code varchar(255);

CREATE TABLE t_mock_project
(
    id           int GENERATED BY DEFAULT AS IDENTITY,
    user_name    varchar(255),
    project_name varchar(255),
    project_code varchar(255),
    status       tinyint,
    description  varchar(1024),
    creator      varchar(255),
    create_date  timestamp,
    modifier     varchar(255),
    modify_date  timestamp,
    PRIMARY KEY (id)
);
