CREATE TABLE t_mock_schema
(
    id                   int GENERATED BY DEFAULT AS IDENTITY,
    request_id           int,
    data_id              int,
    parameters_schema    text,
    request_body_schema  text,
    response_body_schema text,
    create_date          timestamp,
    modifier             varchar(255),
    modify_date          timestamp,
    creator              varchar(255),
    PRIMARY KEY (id)
);
