server:
  port: 8686
spring:
  application:
    name: simple-boot-mock-server
  messages:
    basename: messages
    encoding: UTF-8
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/simple-boot-mock/mockdb;AUTO_SERVER=TRUE
#    url: jdbc:h2:mem:simpledb
    username: root
    password: 123456
    hikari: # 连接池配置
      maximum-pool-size: 5
      minimum-idle: 2
      connection-test-query: select 1;
  h2:
    console:
      enabled: true
  flyway:
    baseline-on-migrate: true
    out-of-order: true
    placeholder-prefix: "${"
    table: flyway_schema_history
    locations: classpath:db/migration
  cache:
    cache-names: mock-meta-data-cache
    caffeine:
      spec: maximumSize=500,expireAfterWrite=300s
mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_
      table-underline: true
    banner: false
logging:
  file:
    name: logs/simple-boot-mock-server.log
    max-size: 10MB
    max-history: 7
    total-size-cap: 0MB
  level: # 日志级别
    root: INFO
    web: DEBUG
    org.springframework: INFO
#  config: classpath:demo-logback.xml