server:
  port: 9086
spring:
  application:
    name: simple-boot-mock-server
  messages:
    basename: messages
    encoding: UTF-8
  datasource:
    driver-class-name: ${MOCK_DB_CLASS_NAME:org.h2.Driver}
    url: ${MOCK_DB_URL:@spring.database.url@}
#    url: jdbc:h2:mem:simpledb
    username: ${MOCK_DB_USERNAME:root}
    password: ${MOCK_DB_PASSWORD:123456}
    hikari: # 连接池配置
      maximum-pool-size: ${MOCK_DB_POOL_SIZE:5}
      minimum-idle: 2
      connection-test-query: select 1;
  h2:
    console:
      enabled: ${MOCK_DB_H2_CONSOLE:false}
      settings:
        web-allow-others: true
  flyway:
    baseline-on-migrate: true
    out-of-order: true
    placeholder-prefix: "${"
    table: flyway_schema_history
    locations: classpath:db/${MOCK_DB_TYPE:h2}/migration
mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_
      table-underline: true
    banner: false
logging: # 日志相关配置
  level:
    root: info
  config: classpath:logback-spring.xml
  file:
    path: ${MOCK_LOG_DIR:~/logs/${spring.application.name}}
    name: ${logging.file.path}/${spring.application.name}.log
