CREATE TABLE t_mock_data
(
    id            int GENERATED BY DEFAULT AS IDENTITY,
    group_id      int,
    request_id    int,
    status        int,
    status_code   int,
    default_flag  int,
    content_type  varchar(255),
    mock_params   text,
    headers       varchar(2048),
    response_body text,
    description   varchar(1024),
    creator       varchar(255),
    create_date   timestamp,
    modifier      varchar(255),
    modify_date   timestamp,
    PRIMARY KEY (id)
);
CREATE TABLE t_mock_group
(
    id          int GENERATED BY DEFAULT AS IDENTITY,
    group_name  varchar(100),
    group_path  varchar(255),
    status      tinyint,
    proxy_url   varchar(2048),
    description varchar(1024),
    creator     varchar(255),
    create_date timestamp,
    modifier    varchar(255),
    modify_date timestamp,
    PRIMARY KEY (id)
);
CREATE TABLE t_mock_request
(
    id           int GENERATED BY DEFAULT AS IDENTITY,
    group_id     int,
    request_path varchar(1000),
    method       varchar(50),
    status       int,
    description  varchar(1024),
    creator      varchar(255),
    create_date  timestamp,
    modifier     varchar(255),
    modify_date  timestamp,
    PRIMARY KEY (id)
);
CREATE TABLE t_mock_user
(
    id            int GENERATED BY DEFAULT AS IDENTITY,
    user_name     varchar(255),
    user_password varchar(255),
    status        int,
    user_email    varchar(2049),
    nick_name     varchar(255),
    creator       varchar(255),
    create_date   timestamp,
    modifier      varchar(255),
    modify_date   timestamp,
    PRIMARY KEY (id)
);
